name: Hello World Workflow
on:
  push:
    branches:
      - master

jobs:
  hello:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Step Say Hello
        env:
          MSG: Hello World
        run: echo $MSG